### ISSUE TITLE
Get error when try to build from source code

### ISSUE THREAD

**Issue by CloudHuang** [jboss-switchyard/switchyard#18]
Error:
```
Missing:
----------
1) org.apache.maven.archetype:archetype-packaging:jar:RELEASE

  Try downloading the file manually from the project website.

  Then, install it using the command:
      mvn install:install-file -DgroupId=org.apache.maven.archetype -DartifactId=archetype-packaging -Dversion=RELEASE -Dpackaging=jar -Dfil
e=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there:
      mvn deploy:deploy-file -DgroupId=org.apache.maven.archetype -DartifactId=archetype-packaging -Dversion=RELEASE -Dpackaging=jar -Dfile=
/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency:
        1) org.switchyard.archetypes:switchyard-application:maven-archetype:2.1.0-SNAPSHOT
        2) org.apache.maven.archetype:archetype-packaging:jar:RELEASE

----------
1 required artifact is missing.

for artifact:
  org.switchyard.archetypes:switchyard-application:maven-archetype:2.1.0-SNAPSHOT

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  fusesource-public-release-repository-group (https://repository.jboss.org/nexus/content/repositories/fs-releases),
  jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/),
  jboss-enterprise-techpreview-group (http://maven.repository.redhat.com/techpreview/all/)

```

OS: win7 64bit
Maven: 2.2.1 ( regarding to switchyard core README file )
Java: 
>java version "1.8.0_45"
>Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
>Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by CloudHuang** [comment]
Another issue is cannot find the camel-sap artifact

> [ERROR] Failed to execute goal on project switchyard-component-camel-sap: Could not resolve dependencies for project org.switchyard.componen
ts:switchyard-component-camel-sap:bundle:2.0.0.Final: Failure to find org.fusesource:camel-sap:jar:6.2.0.redhat-064 in https://repository.jboss.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-public-repository-group has elapsed or updates are forced -> [Help 1]

**Comment by CloudHuang** [comment]
JDK8 is not support?

**Comment by cunningt** [comment]
Please start a thread here detailing the build issues you are having, JDK/maven used, and errors you see here -

https://developer.jboss.org/en/switchyard?view=discussions

It's been a month or two since I've tried it, but I believe JDK8 is fine for building.    There may be one test that fails under JDK 8 but I believe it has been temporarily excluded.
